version: '3.8'

services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - '--providers.docker'
      - '--providers.docker.exposedbydefault=false'
      - '--entryPoints.websecure.address=:443'
      - '--certificatesresolvers.myresolver.acme.tlschallenge=true'
      - '--certificatesresolvers.myresolver.acme.email=amadu@chefama.blog'
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.web.http.redirections.entrypoint.to=websecure'
      - '--entrypoints.web.http.redirections.entrypoint.scheme=https'
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
  amablog:
    image: ghcr.io/amaduswaray/amablog:latest
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.amablog.rule=Host(`chefama.blog`)'
      - 'traefik.http.routers.amablog.entrypoints=websecure'
      - 'traefik.http.routers.amablog.tls.certresolver=myresolver'
    environment:
      - NODE_ENV=production
    deploy:
      mode: replicated
      replicas: 3
    restart: always
volumes:
  letsencrypt:
